# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12lF1LTk6KMKfbFjGaHlW47Q-nCYiEdUZ
"""

import pandas as pd
import numpy as np

ar = np.array([2,1,6,4,3,2,8,1,5])

Mean= np.sum(ar)/len(ar)
print(Mean)

np.mean(ar)